// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Url struct {
	ID          int64
	ShortCode   string
	OriginalUrl string
	CreatedAt   time.Time
}
